apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: test-app
  labels:
    app: app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: deployment
          image: tne729/petclinc:main
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: petclinc-service-primary
  namespace: test-app
  annotations:
    harness.io/primary-service: "true"
spec:
  type: ClusterIP
  selector:
    app: petclinc
    version: blue
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: petclinc-service-stage
  namespace: test-app
  annotations:
    harness.io/stage-service: "true"
spec:
  type: ClusterIP
  selector:
    app: petclinc
    version: green
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petclinc-pdb
  namespace: test-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: petclinc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinc-hpa
  namespace: test-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinc-blue
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
