apiVersion: v1
kind: Service
metadata:
  name: petclinc-service-primary
  namespace: test-app
  annotations:
    harness.io/direct-apply: "true"
    harness.io/primary-service: "true"
spec:
  type: ClusterIP
  selector:
    app: petclinc
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: petclinc-service-stage
  namespace: test-app
  annotations:
    harness.io/direct-apply: "true"
    harness.io/stage-service: "true"
spec:
  type: ClusterIP
  selector:
    app: petclinc
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petclinc-pdb
  namespace: test-app
  annotations:
    harness.io/direct-apply: "true"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: petclinc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinc-hpa
  namespace: test-app
  annotations:
    harness.io/direct-apply: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment-blue
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
